volumes:
  pg_data:
  static:
  media:
  frontend:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    restart: on-failure
    volumes:
      - static:/app/static
      - media:/media

  frontend:
    build: ./frontend/
    volumes:
      - frontend:/app/build

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
      - frontend:/frontend
    depends_on:
      - backend
      - frontend